/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cedriclevasseur.tetris.config.color;

import java.util.ArrayList;
import java.util.List;
import lombok.Data;

/**
 *
 * @author cedric
 */
public @Data abstract class Color {


    public abstract String getColorMain();

    public abstract String getColorLight();

    public abstract String getColorDark();

    public String name = this.getClass().getName();

    public static List<Color> listOfColor = new ArrayList<>();

    //not generated by lombok because of static
    public static List<Color> getListOfColor() {
        return listOfColor;
    }

    public Color() {
        listOfColor.add(new Blue());
        listOfColor.add(new Red());
        listOfColor.add(new Grey());
        listOfColor.add(new Green());
    }
}
